
	 
	/*
	 *	This content is generated from the API File Info.
	 *	(Alt+Shift+Ctrl+I).
	 *
	 *	@desc 		
	 *	@file 		artboard_3_copy
	 *	@date 		0
	 *	@title 		Artboard 3 copy
	 *	@author 	
	 *	@keywords 	
	 *	@generator 	Export Kit v1.3.xd
	 *
	 */
	

package com.flash.activities;

import android.app.Activity;
import android.os.Bundle;


import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

import com.flash.R;

	public class artboard_3_copy_activity extends Activity {

	
	private View _bg__artboard_3_copy;
	private View rectangle_52;
	private ImageView group_135;
	private View rectangle_54;
	private ImageView path_198;
	private ImageView path_199;
	private ImageView path_200;
	private ImageView path_201;
	private ImageView path_202;
	private ImageView path_203;
	private ImageView path_204;
	private ImageView path_205;
	private ImageView path_206;
	private ImageView path_207;
	private ImageView path_208;
	private ImageView path_209;
	private ImageView path_210;
	private ImageView path_211;
	private ImageView path_212;
	private ImageView path_213;
	private ImageView path_214;
	private ImageView path_215;
	private ImageView path_216;
	private ImageView path_217;
	private ImageView path_218;
	private ImageView path_219;
	private ImageView path_220;
	private ImageView path_221;
	private ImageView path_222;
	private ImageView path_223;
	private ImageView path_224;
	private ImageView path_225;
	private ImageView path_226;
	private ImageView path_227;
	private ImageView path_228;
	private ImageView path_229;
	private ImageView path_230;
	private ImageView path_231;
	private View ellipse_13;
	private ImageView path_232;
	private View ellipse_14;
	private ImageView path_233;
	private ImageView path_234;
	private ImageView path_235;
	private ImageView path_236;
	private ImageView path_237;
	private ImageView path_238;
	private ImageView path_239;
	private ImageView path_240;
	private ImageView path_241;
	private ImageView path_242;
	private ImageView path_243;
	private ImageView path_244;
	private ImageView path_245;
	private ImageView path_246;
	private ImageView path_247;
	private ImageView path_248;
	private ImageView path_249;
	private ImageView path_250;
	private ImageView path_251;
	private ImageView path_252;
	private ImageView path_253;
	private ImageView path_254;
	private ImageView path_255;
	private ImageView path_256;
	private ImageView path_257;
	private ImageView path_258;
	private ImageView path_259;
	private ImageView path_260;
	private ImageView path_261;
	private ImageView path_262;
	private ImageView path_263;
	private ImageView path_264;
	private ImageView path_265;
	private View ellipse_15;
	private ImageView path_266;
	private ImageView path_267;
	private ImageView path_268;
	private ImageView path_269;
	private ImageView path_270;
	private View ellipse_16;
	private ImageView path_271;
	private View ellipse_17;
	private ImageView path_272;
	private ImageView path_273;
	private ImageView path_274;
	private ImageView path_275;
	private ImageView path_276;
	private ImageView path_277;
	private ImageView path_278;
	private ImageView path_279;
	private ImageView path_280;
	private ImageView path_281;
	private ImageView path_282;
	private ImageView path_283;
	private ImageView path_284;
	private ImageView path_285;
	private ImageView path_286;
	private ImageView path_287;
	private ImageView path_288;
	private ImageView path_289;
	private View ellipse_18;
	private ImageView path_290;
	private ImageView path_291;
	private ImageView path_292;
	private ImageView path_293;
	private ImageView path_294;
	private ImageView path_295;
	private ImageView path_296;
	private ImageView path_297;
	private ImageView path_298;
	private ImageView path_299;
	private ImageView path_300;
	private ImageView path_301;
	private ImageView path_302;
	private ImageView path_303;
	private View ellipse_19;
	private ImageView path_304;
	private ImageView path_305;
	private ImageView path_306;
	private ImageView path_307;
	private ImageView path_308;
	private ImageView path_309;
	private ImageView path_310;
	private ImageView path_311;
	private ImageView path_312;
	private ImageView path_313;
	private ImageView path_314;
	private ImageView path_315;
	private ImageView path_316;
	private ImageView path_317;
	private ImageView path_318;
	private View ellipse_20;
	private View ellipse_21;
	private ImageView path_319;
	private ImageView path_320;
	private ImageView path_321;
	private ImageView path_322;
	private ImageView path_323;
	private ImageView path_324;
	private ImageView path_325;
	private ImageView path_326;
	private ImageView path_327;
	private ImageView path_328;
	private ImageView path_329;
	private ImageView path_330;
	private ImageView path_331;
	private ImageView path_332;
	private ImageView path_333;
	private ImageView path_334;
	private ImageView path_335;
	private ImageView path_336;
	private ImageView path_337;
	private ImageView path_338;
	private ImageView path_339;
	private ImageView path_340;
	private ImageView path_341;
	private ImageView path_342;
	private ImageView path_343;
	private ImageView path_344;
	private ImageView path_345;
	private ImageView path_346;
	private ImageView path_347;
	private ImageView path_348;
	private ImageView path_349;
	private ImageView path_350;
	private View ellipse_22;
	private ImageView path_351;
	private ImageView path_352;
	private ImageView path_353;
	private ImageView path_354;
	private ImageView path_355;
	private ImageView path_356;
	private ImageView path_357;
	private ImageView path_358;
	private ImageView path_359;
	private ImageView path_360;
	private ImageView path_361;
	private ImageView path_362;
	private ImageView path_363;
	private View ellipse_23;
	private ImageView path_364;
	private View ellipse_24;
	private ImageView path_365;
	private View ellipse_25;
	private ImageView path_366;
	private View ellipse_26;
	private ImageView path_367;
	private ImageView path_368;
	private ImageView path_369;
	private ImageView path_370;
	private ImageView path_371;
	private ImageView path_372;
	private ImageView path_373;
	private View ellipse_27;
	private ImageView path_374;
	private ImageView path_375;
	private ImageView path_376;
	private ImageView path_377;
	private ImageView path_378;
	private ImageView path_379;
	private ImageView path_380;
	private ImageView path_381;
	private ImageView path_382;
	private ImageView rectangle_55;
	private ImageView path_383;
	private ImageView path_384;
	private ImageView path_385;
	private ImageView path_386;
	private TextView according_to_ilo_about_4_of_each_5_workers_has_been_affacted_by_covid19____flash_app_brought_the_chance_to_them_again_to_earn_their_living_;
	private View ellipse_28;
	private View ellipse_29;
	private View ellipse_30;
	private View ellipse_31;
	private ImageView path_389;

	@Override
	public void onCreate(Bundle savedInstanceState) {

		super.onCreate(savedInstanceState);
		setContentView(R.layout.artboard_3_copy);

		
		_bg__artboard_3_copy = (View) findViewById(R.id._bg__artboard_3_copy);
		rectangle_52 = (View) findViewById(R.id.rectangle_52);
		group_135 = (ImageView) findViewById(R.id.group_135);
		rectangle_54 = (View) findViewById(R.id.rectangle_54);
		path_198 = (ImageView) findViewById(R.id.path_198);
		path_199 = (ImageView) findViewById(R.id.path_199);
		path_200 = (ImageView) findViewById(R.id.path_200);
		path_201 = (ImageView) findViewById(R.id.path_201);
		path_202 = (ImageView) findViewById(R.id.path_202);
		path_203 = (ImageView) findViewById(R.id.path_203);
		path_204 = (ImageView) findViewById(R.id.path_204);
		path_205 = (ImageView) findViewById(R.id.path_205);
		path_206 = (ImageView) findViewById(R.id.path_206);
		path_207 = (ImageView) findViewById(R.id.path_207);
		path_208 = (ImageView) findViewById(R.id.path_208);
		path_209 = (ImageView) findViewById(R.id.path_209);
		path_210 = (ImageView) findViewById(R.id.path_210);
		path_211 = (ImageView) findViewById(R.id.path_211);
		path_212 = (ImageView) findViewById(R.id.path_212);
		path_213 = (ImageView) findViewById(R.id.path_213);
		path_214 = (ImageView) findViewById(R.id.path_214);
		path_215 = (ImageView) findViewById(R.id.path_215);
		path_216 = (ImageView) findViewById(R.id.path_216);
		path_217 = (ImageView) findViewById(R.id.path_217);
		path_218 = (ImageView) findViewById(R.id.path_218);
		path_219 = (ImageView) findViewById(R.id.path_219);
		path_220 = (ImageView) findViewById(R.id.path_220);
		path_221 = (ImageView) findViewById(R.id.path_221);
		path_222 = (ImageView) findViewById(R.id.path_222);
		path_223 = (ImageView) findViewById(R.id.path_223);
		path_224 = (ImageView) findViewById(R.id.path_224);
		path_225 = (ImageView) findViewById(R.id.path_225);
		path_226 = (ImageView) findViewById(R.id.path_226);
		path_227 = (ImageView) findViewById(R.id.path_227);
		path_228 = (ImageView) findViewById(R.id.path_228);
		path_229 = (ImageView) findViewById(R.id.path_229);
		path_230 = (ImageView) findViewById(R.id.path_230);
		path_231 = (ImageView) findViewById(R.id.path_231);
		ellipse_13 = (View) findViewById(R.id.ellipse_13);
		path_232 = (ImageView) findViewById(R.id.path_232);
		ellipse_14 = (View) findViewById(R.id.ellipse_14);
		path_233 = (ImageView) findViewById(R.id.path_233);
		path_234 = (ImageView) findViewById(R.id.path_234);
		path_235 = (ImageView) findViewById(R.id.path_235);
		path_236 = (ImageView) findViewById(R.id.path_236);
		path_237 = (ImageView) findViewById(R.id.path_237);
		path_238 = (ImageView) findViewById(R.id.path_238);
		path_239 = (ImageView) findViewById(R.id.path_239);
		path_240 = (ImageView) findViewById(R.id.path_240);
		path_241 = (ImageView) findViewById(R.id.path_241);
		path_242 = (ImageView) findViewById(R.id.path_242);
		path_243 = (ImageView) findViewById(R.id.path_243);
		path_244 = (ImageView) findViewById(R.id.path_244);
		path_245 = (ImageView) findViewById(R.id.path_245);
		path_246 = (ImageView) findViewById(R.id.path_246);
		path_247 = (ImageView) findViewById(R.id.path_247);
		path_248 = (ImageView) findViewById(R.id.path_248);
		path_249 = (ImageView) findViewById(R.id.path_249);
		path_250 = (ImageView) findViewById(R.id.path_250);
		path_251 = (ImageView) findViewById(R.id.path_251);
		path_252 = (ImageView) findViewById(R.id.path_252);
		path_253 = (ImageView) findViewById(R.id.path_253);
		path_254 = (ImageView) findViewById(R.id.path_254);
		path_255 = (ImageView) findViewById(R.id.path_255);
		path_256 = (ImageView) findViewById(R.id.path_256);
		path_257 = (ImageView) findViewById(R.id.path_257);
		path_258 = (ImageView) findViewById(R.id.path_258);
		path_259 = (ImageView) findViewById(R.id.path_259);
		path_260 = (ImageView) findViewById(R.id.path_260);
		path_261 = (ImageView) findViewById(R.id.path_261);
		path_262 = (ImageView) findViewById(R.id.path_262);
		path_263 = (ImageView) findViewById(R.id.path_263);
		path_264 = (ImageView) findViewById(R.id.path_264);
		path_265 = (ImageView) findViewById(R.id.path_265);
		ellipse_15 = (View) findViewById(R.id.ellipse_15);
		path_266 = (ImageView) findViewById(R.id.path_266);
		path_267 = (ImageView) findViewById(R.id.path_267);
		path_268 = (ImageView) findViewById(R.id.path_268);
		path_269 = (ImageView) findViewById(R.id.path_269);
		path_270 = (ImageView) findViewById(R.id.path_270);
		ellipse_16 = (View) findViewById(R.id.ellipse_16);
		path_271 = (ImageView) findViewById(R.id.path_271);
		ellipse_17 = (View) findViewById(R.id.ellipse_17);
		path_272 = (ImageView) findViewById(R.id.path_272);
		path_273 = (ImageView) findViewById(R.id.path_273);
		path_274 = (ImageView) findViewById(R.id.path_274);
		path_275 = (ImageView) findViewById(R.id.path_275);
		path_276 = (ImageView) findViewById(R.id.path_276);
		path_277 = (ImageView) findViewById(R.id.path_277);
		path_278 = (ImageView) findViewById(R.id.path_278);
		path_279 = (ImageView) findViewById(R.id.path_279);
		path_280 = (ImageView) findViewById(R.id.path_280);
		path_281 = (ImageView) findViewById(R.id.path_281);
		path_282 = (ImageView) findViewById(R.id.path_282);
		path_283 = (ImageView) findViewById(R.id.path_283);
		path_284 = (ImageView) findViewById(R.id.path_284);
		path_285 = (ImageView) findViewById(R.id.path_285);
		path_286 = (ImageView) findViewById(R.id.path_286);
		path_287 = (ImageView) findViewById(R.id.path_287);
		path_288 = (ImageView) findViewById(R.id.path_288);
		path_289 = (ImageView) findViewById(R.id.path_289);
		ellipse_18 = (View) findViewById(R.id.ellipse_18);
		path_290 = (ImageView) findViewById(R.id.path_290);
		path_291 = (ImageView) findViewById(R.id.path_291);
		path_292 = (ImageView) findViewById(R.id.path_292);
		path_293 = (ImageView) findViewById(R.id.path_293);
		path_294 = (ImageView) findViewById(R.id.path_294);
		path_295 = (ImageView) findViewById(R.id.path_295);
		path_296 = (ImageView) findViewById(R.id.path_296);
		path_297 = (ImageView) findViewById(R.id.path_297);
		path_298 = (ImageView) findViewById(R.id.path_298);
		path_299 = (ImageView) findViewById(R.id.path_299);
		path_300 = (ImageView) findViewById(R.id.path_300);
		path_301 = (ImageView) findViewById(R.id.path_301);
		path_302 = (ImageView) findViewById(R.id.path_302);
		path_303 = (ImageView) findViewById(R.id.path_303);
		ellipse_19 = (View) findViewById(R.id.ellipse_19);
		path_304 = (ImageView) findViewById(R.id.path_304);
		path_305 = (ImageView) findViewById(R.id.path_305);
		path_306 = (ImageView) findViewById(R.id.path_306);
		path_307 = (ImageView) findViewById(R.id.path_307);
		path_308 = (ImageView) findViewById(R.id.path_308);
		path_309 = (ImageView) findViewById(R.id.path_309);
		path_310 = (ImageView) findViewById(R.id.path_310);
		path_311 = (ImageView) findViewById(R.id.path_311);
		path_312 = (ImageView) findViewById(R.id.path_312);
		path_313 = (ImageView) findViewById(R.id.path_313);
		path_314 = (ImageView) findViewById(R.id.path_314);
		path_315 = (ImageView) findViewById(R.id.path_315);
		path_316 = (ImageView) findViewById(R.id.path_316);
		path_317 = (ImageView) findViewById(R.id.path_317);
		path_318 = (ImageView) findViewById(R.id.path_318);
		ellipse_20 = (View) findViewById(R.id.ellipse_20);
		ellipse_21 = (View) findViewById(R.id.ellipse_21);
		path_319 = (ImageView) findViewById(R.id.path_319);
		path_320 = (ImageView) findViewById(R.id.path_320);
		path_321 = (ImageView) findViewById(R.id.path_321);
		path_322 = (ImageView) findViewById(R.id.path_322);
		path_323 = (ImageView) findViewById(R.id.path_323);
		path_324 = (ImageView) findViewById(R.id.path_324);
		path_325 = (ImageView) findViewById(R.id.path_325);
		path_326 = (ImageView) findViewById(R.id.path_326);
		path_327 = (ImageView) findViewById(R.id.path_327);
		path_328 = (ImageView) findViewById(R.id.path_328);
		path_329 = (ImageView) findViewById(R.id.path_329);
		path_330 = (ImageView) findViewById(R.id.path_330);
		path_331 = (ImageView) findViewById(R.id.path_331);
		path_332 = (ImageView) findViewById(R.id.path_332);
		path_333 = (ImageView) findViewById(R.id.path_333);
		path_334 = (ImageView) findViewById(R.id.path_334);
		path_335 = (ImageView) findViewById(R.id.path_335);
		path_336 = (ImageView) findViewById(R.id.path_336);
		path_337 = (ImageView) findViewById(R.id.path_337);
		path_338 = (ImageView) findViewById(R.id.path_338);
		path_339 = (ImageView) findViewById(R.id.path_339);
		path_340 = (ImageView) findViewById(R.id.path_340);
		path_341 = (ImageView) findViewById(R.id.path_341);
		path_342 = (ImageView) findViewById(R.id.path_342);
		path_343 = (ImageView) findViewById(R.id.path_343);
		path_344 = (ImageView) findViewById(R.id.path_344);
		path_345 = (ImageView) findViewById(R.id.path_345);
		path_346 = (ImageView) findViewById(R.id.path_346);
		path_347 = (ImageView) findViewById(R.id.path_347);
		path_348 = (ImageView) findViewById(R.id.path_348);
		path_349 = (ImageView) findViewById(R.id.path_349);
		path_350 = (ImageView) findViewById(R.id.path_350);
		ellipse_22 = (View) findViewById(R.id.ellipse_22);
		path_351 = (ImageView) findViewById(R.id.path_351);
		path_352 = (ImageView) findViewById(R.id.path_352);
		path_353 = (ImageView) findViewById(R.id.path_353);
		path_354 = (ImageView) findViewById(R.id.path_354);
		path_355 = (ImageView) findViewById(R.id.path_355);
		path_356 = (ImageView) findViewById(R.id.path_356);
		path_357 = (ImageView) findViewById(R.id.path_357);
		path_358 = (ImageView) findViewById(R.id.path_358);
		path_359 = (ImageView) findViewById(R.id.path_359);
		path_360 = (ImageView) findViewById(R.id.path_360);
		path_361 = (ImageView) findViewById(R.id.path_361);
		path_362 = (ImageView) findViewById(R.id.path_362);
		path_363 = (ImageView) findViewById(R.id.path_363);
		ellipse_23 = (View) findViewById(R.id.ellipse_23);
		path_364 = (ImageView) findViewById(R.id.path_364);
		ellipse_24 = (View) findViewById(R.id.ellipse_24);
		path_365 = (ImageView) findViewById(R.id.path_365);
		ellipse_25 = (View) findViewById(R.id.ellipse_25);
		path_366 = (ImageView) findViewById(R.id.path_366);
		ellipse_26 = (View) findViewById(R.id.ellipse_26);
		path_367 = (ImageView) findViewById(R.id.path_367);
		path_368 = (ImageView) findViewById(R.id.path_368);
		path_369 = (ImageView) findViewById(R.id.path_369);
		path_370 = (ImageView) findViewById(R.id.path_370);
		path_371 = (ImageView) findViewById(R.id.path_371);
		path_372 = (ImageView) findViewById(R.id.path_372);
		path_373 = (ImageView) findViewById(R.id.path_373);
		ellipse_27 = (View) findViewById(R.id.ellipse_27);
		path_374 = (ImageView) findViewById(R.id.path_374);
		path_375 = (ImageView) findViewById(R.id.path_375);
		path_376 = (ImageView) findViewById(R.id.path_376);
		path_377 = (ImageView) findViewById(R.id.path_377);
		path_378 = (ImageView) findViewById(R.id.path_378);
		path_379 = (ImageView) findViewById(R.id.path_379);
		path_380 = (ImageView) findViewById(R.id.path_380);
		path_381 = (ImageView) findViewById(R.id.path_381);
		path_382 = (ImageView) findViewById(R.id.path_382);
		rectangle_55 = (ImageView) findViewById(R.id.rectangle_55);
		path_383 = (ImageView) findViewById(R.id.path_383);
		path_384 = (ImageView) findViewById(R.id.path_384);
		path_385 = (ImageView) findViewById(R.id.path_385);
		path_386 = (ImageView) findViewById(R.id.path_386);
		according_to_ilo_about_4_of_each_5_workers_has_been_affacted_by_covid19____flash_app_brought_the_chance_to_them_again_to_earn_their_living_ = (TextView) findViewById(R.id.according_to_ilo_about_4_of_each_5_workers_has_been_affacted_by_covid19____flash_app_brought_the_chance_to_them_again_to_earn_their_living_);
		ellipse_28 = (View) findViewById(R.id.ellipse_28);
		ellipse_29 = (View) findViewById(R.id.ellipse_29);
		ellipse_30 = (View) findViewById(R.id.ellipse_30);
		ellipse_31 = (View) findViewById(R.id.ellipse_31);
		path_389 = (ImageView) findViewById(R.id.path_389);
	
		
		//custom code goes here
	
	}
}
	
	